Simulink.defineIntEnumType('LedStatus', ... 
	{'OFF', 'ON', 'INVALID'}, ...
	[0;1;2], ... 
	'Description', 'Led Status', ...
	'DefaultValue', 'OFF', ...
	'DataScope', 'Auto', ...
	'AddClassNameToEnumNames', true, ...
	'StorageType', 'uint8');


