% -------------------------------------------------------------------
%  Generated by MATLAB on 25-Apr-2020 22:54:25
%  MATLAB version: 9.4.0.813654 (R2018a)
% -------------------------------------------------------------------
%Config Parameter of the Project


TcpBufferSize=10;

TcpBufferInit=zeros(1,TcpBufferSize);

LedOnText="ON";

LedOffText="OFF";

TcpServerRxPort = 25000;
TcpServerTxPort = 25000;

TcpServerRxTimeOut = 0.2;

TcpServerTxTimeOut = 0.5;


LedOnMessage='L.E.D is ON    '
LedOffMessage="L.E.D is OFF   "
LedInValidCommandMessage='Invalid Command'